-- 1. Crear la tabla
CREATE TABLE favorito (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    usuario_id BIGINT NOT NULL,
    restaurante_id BIGINT NOT NULL,
    fecha_creacion TIMESTAMP,
    
    CONSTRAINT pk_favorito PRIMARY KEY (id)
);

-- 2. Agregar la Clave Foránea (Relación con Restaurante)
ALTER TABLE favorito 
    ADD CONSTRAINT fk_favorito_restaurante 
    FOREIGN KEY (restaurante_id) 
    REFERENCES restaurante (id);

-- 3. Agregar la Restricción Única (Un usuario solo puede dar like una vez al mismo restaurante)
ALTER TABLE favorito 
    ADD CONSTRAINT uq_favorito_usuario_restaurante 
    UNIQUE (usuario_id, restaurante_id);